// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// xhdfe_cpp_fit
Rcpp::List xhdfe_cpp_fit(Rcpp::NumericVector y, Rcpp::NumericMatrix X, Rcpp::List fes, SEXP weights, Rcpp::List clusters, SEXP instruments, Rcpp::IntegerVector endogenous_idx, Rcpp::List slopes, SEXP group, SEXP individual, std::string aggregation, Rcpp::List opts);
RcppExport SEXP _xhdfe_xhdfe_cpp_fit(SEXP ySEXP, SEXP XSEXP, SEXP fesSEXP, SEXP weightsSEXP, SEXP clustersSEXP, SEXP instrumentsSEXP, SEXP endogenous_idxSEXP, SEXP slopesSEXP, SEXP groupSEXP, SEXP individualSEXP, SEXP aggregationSEXP, SEXP optsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type fes(fesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type clusters(clustersSEXP);
    Rcpp::traits::input_parameter< SEXP >::type instruments(instrumentsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type endogenous_idx(endogenous_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type slopes(slopesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type group(groupSEXP);
    Rcpp::traits::input_parameter< SEXP >::type individual(individualSEXP);
    Rcpp::traits::input_parameter< std::string >::type aggregation(aggregationSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type opts(optsSEXP);
    rcpp_result_gen = Rcpp::wrap(xhdfe_cpp_fit(y, X, fes, weights, clusters, instruments, endogenous_idx, slopes, group, individual, aggregation, opts));
    return rcpp_result_gen;
END_RCPP
}
// xhdfe_cpp_partial_out
Rcpp::List xhdfe_cpp_partial_out(Rcpp::NumericVector y, Rcpp::NumericMatrix X, Rcpp::List fes, SEXP weights, Rcpp::List slopes, Rcpp::List opts);
RcppExport SEXP _xhdfe_xhdfe_cpp_partial_out(SEXP ySEXP, SEXP XSEXP, SEXP fesSEXP, SEXP weightsSEXP, SEXP slopesSEXP, SEXP optsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type fes(fesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type slopes(slopesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type opts(optsSEXP);
    rcpp_result_gen = Rcpp::wrap(xhdfe_cpp_partial_out(y, X, fes, weights, slopes, opts));
    return rcpp_result_gen;
END_RCPP
}
// xhdfe_cpp_extract_group_fes
Rcpp::List xhdfe_cpp_extract_group_fes(Rcpp::NumericVector y, Rcpp::NumericMatrix X, Rcpp::List fes, Rcpp::IntegerVector group, Rcpp::IntegerVector individual, SEXP weights, std::string aggregation, Rcpp::List gi_opts, Rcpp::List opts);
RcppExport SEXP _xhdfe_xhdfe_cpp_extract_group_fes(SEXP ySEXP, SEXP XSEXP, SEXP fesSEXP, SEXP groupSEXP, SEXP individualSEXP, SEXP weightsSEXP, SEXP aggregationSEXP, SEXP gi_optsSEXP, SEXP optsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type fes(fesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type individual(individualSEXP);
    Rcpp::traits::input_parameter< SEXP >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< std::string >::type aggregation(aggregationSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type gi_opts(gi_optsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type opts(optsSEXP);
    rcpp_result_gen = Rcpp::wrap(xhdfe_cpp_extract_group_fes(y, X, fes, group, individual, weights, aggregation, gi_opts, opts));
    return rcpp_result_gen;
END_RCPP
}
// xhdfe_cpp_build_info
Rcpp::List xhdfe_cpp_build_info();
RcppExport SEXP _xhdfe_xhdfe_cpp_build_info() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(xhdfe_cpp_build_info());
    return rcpp_result_gen;
END_RCPP
}
// xhdfe_cpp_akm_leave_out_set
Rcpp::List xhdfe_cpp_akm_leave_out_set(Rcpp::IntegerVector worker, Rcpp::IntegerVector firm);
RcppExport SEXP _xhdfe_xhdfe_cpp_akm_leave_out_set(SEXP workerSEXP, SEXP firmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type worker(workerSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type firm(firmSEXP);
    rcpp_result_gen = Rcpp::wrap(xhdfe_cpp_akm_leave_out_set(worker, firm));
    return rcpp_result_gen;
END_RCPP
}
// xhdfe_cpp_akm_kss
Rcpp::List xhdfe_cpp_akm_kss(Rcpp::NumericVector y, Rcpp::IntegerVector worker, Rcpp::IntegerVector firm, SEXP X, Rcpp::List opts, SEXP fweights);
RcppExport SEXP _xhdfe_xhdfe_cpp_akm_kss(SEXP ySEXP, SEXP workerSEXP, SEXP firmSEXP, SEXP XSEXP, SEXP optsSEXP, SEXP fweightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type worker(workerSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type firm(firmSEXP);
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type opts(optsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fweights(fweightsSEXP);
    rcpp_result_gen = Rcpp::wrap(xhdfe_cpp_akm_kss(y, worker, firm, X, opts, fweights));
    return rcpp_result_gen;
END_RCPP
}
// xhdfe_cpp_gelbach
Rcpp::List xhdfe_cpp_gelbach(Rcpp::NumericVector y, Rcpp::NumericMatrix X1, SEXP X2, Rcpp::IntegerVector x2_group_sizes, Rcpp::List fes, SEXP cluster, std::string vce, bool gamma0, bool cov0, double tol, int num_threads, SEXP weights, bool fweights, Rcpp::IntegerVector absorbed_x1);
RcppExport SEXP _xhdfe_xhdfe_cpp_gelbach(SEXP ySEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP x2_group_sizesSEXP, SEXP fesSEXP, SEXP clusterSEXP, SEXP vceSEXP, SEXP gamma0SEXP, SEXP cov0SEXP, SEXP tolSEXP, SEXP num_threadsSEXP, SEXP weightsSEXP, SEXP fweightsSEXP, SEXP absorbed_x1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type x2_group_sizes(x2_group_sizesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type fes(fesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type cluster(clusterSEXP);
    Rcpp::traits::input_parameter< std::string >::type vce(vceSEXP);
    Rcpp::traits::input_parameter< bool >::type gamma0(gamma0SEXP);
    Rcpp::traits::input_parameter< bool >::type cov0(cov0SEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type fweights(fweightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type absorbed_x1(absorbed_x1SEXP);
    rcpp_result_gen = Rcpp::wrap(xhdfe_cpp_gelbach(y, X1, X2, x2_group_sizes, fes, cluster, vce, gamma0, cov0, tol, num_threads, weights, fweights, absorbed_x1));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_xhdfe_xhdfe_cpp_fit", (DL_FUNC) &_xhdfe_xhdfe_cpp_fit, 12},
    {"_xhdfe_xhdfe_cpp_partial_out", (DL_FUNC) &_xhdfe_xhdfe_cpp_partial_out, 6},
    {"_xhdfe_xhdfe_cpp_extract_group_fes", (DL_FUNC) &_xhdfe_xhdfe_cpp_extract_group_fes, 9},
    {"_xhdfe_xhdfe_cpp_build_info", (DL_FUNC) &_xhdfe_xhdfe_cpp_build_info, 0},
    {"_xhdfe_xhdfe_cpp_akm_leave_out_set", (DL_FUNC) &_xhdfe_xhdfe_cpp_akm_leave_out_set, 2},
    {"_xhdfe_xhdfe_cpp_akm_kss", (DL_FUNC) &_xhdfe_xhdfe_cpp_akm_kss, 6},
    {"_xhdfe_xhdfe_cpp_gelbach", (DL_FUNC) &_xhdfe_xhdfe_cpp_gelbach, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_xhdfe(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
