# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.xhdfe_cpp_fit <- function(y, X, fes, weights, clusters, instruments, endogenous_idx, slopes, group, individual, aggregation, opts) {
    .Call(`_xhdfe_xhdfe_cpp_fit`, y, X, fes, weights, clusters, instruments, endogenous_idx, slopes, group, individual, aggregation, opts)
}

.xhdfe_cpp_partial_out <- function(y, X, fes, weights, slopes, opts) {
    .Call(`_xhdfe_xhdfe_cpp_partial_out`, y, X, fes, weights, slopes, opts)
}

.xhdfe_cpp_extract_group_fes <- function(y, X, fes, group, individual, weights, aggregation, gi_opts, opts) {
    .Call(`_xhdfe_xhdfe_cpp_extract_group_fes`, y, X, fes, group, individual, weights, aggregation, gi_opts, opts)
}

.xhdfe_cpp_build_info <- function() {
    .Call(`_xhdfe_xhdfe_cpp_build_info`)
}

